[package]
name = "rocket-game"
version = "0.1.1"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "GPL-3.0"
homepage = "https://github.com/tversteeg/rocket-game"

readme = "README.md"
description = "A small asteroids like game"

repository = "https://github.com/tversteeg/rocket-game.git"
keywords = ["game", "asteroids", "vector"]
categories = ["games"]

build = "build.rs"

[badges]
travis-ci = {repository = "tversteeg/rocket-game"}

[dependencies]
ggez = "0.4"
gfx = "0.17"

[build-dependencies]
image = "0.18"
distance-field = "0.1"
